import type { OpenAI } from 'openai';

/**
 * Encapsulates the result of a translation request, including the translated
 * content, token usage statistics, and any model refusal message.
 *
 * @typeParam TContent - The type of the translated content (defaults to `string[]`).
 */
export class TranslationOutput<TContent = string[]> {
  /** The translated content returned by the model. */
  content: TContent;
  /** Number of tokens in the prompt sent to the model. */
  promptTokens: number;
  /** Number of tokens generated by the model. */
  completionTokens: number;
  /** Number of prompt tokens served from cache. */
  cachedTokens: number;
  /** Total tokens consumed (prompt + completion). */
  totalTokens: number;
  /** Model refusal message, or an empty string if none. */
  refusal: string;

  /**
   * Creates a new translation output.
   *
   * @param content - The translated content.
   * @param promptTokens - Prompt token count (defaults to 0).
   * @param completionTokens - Completion token count (defaults to 0).
   * @param cachedTokens - Cached prompt token count (defaults to 0).
   * @param totalTokens - Total tokens (defaults to `promptTokens + completionTokens`).
   * @param refusal - Model refusal message, if any.
   */
  constructor(
    content: TContent,
    promptTokens: number | undefined,
    completionTokens: number | undefined,
    cachedTokens: number | undefined,
    totalTokens?: number,
    refusal: string = '',
  ) {
    this.content = content;
    this.promptTokens = promptTokens ?? 0;
    this.completionTokens = completionTokens ?? 0;
    this.cachedTokens = cachedTokens ?? 0;
    this.totalTokens = totalTokens ?? (this.promptTokens + this.completionTokens);
    this.refusal = refusal;
  }

  /**
   * Creates a {@link TranslationOutput} from a non-streaming chat completion response.
   *
   * Extracts token usage and refusal information from the completion object.
   *
   * @typeParam C - The type of the translated content.
   * @param content - The translated content to wrap.
   * @param completion - The full OpenAI chat completion response.
   * @returns A new {@link TranslationOutput} populated with usage data.
   */
  static fromCompletion<C = string[]>(
    content: C,
    completion: OpenAI.Chat.ChatCompletion,
  ): TranslationOutput<C> {
    const usage = completion.usage;
    return new TranslationOutput(
      content,
      usage?.prompt_tokens,
      usage?.completion_tokens,
      usage?.prompt_tokens_details?.cached_tokens,
      usage?.total_tokens,
      completion.choices[0]?.message?.refusal ?? undefined,
    );
  }

  /**
   * Creates a {@link TranslationOutput} from a standalone usage object
   * (typically obtained from a streaming completion).
   *
   * @typeParam C - The type of the translated content.
   * @param content - The translated content to wrap.
   * @param usage - The token usage statistics, or `undefined` if unavailable.
   * @returns A new {@link TranslationOutput} populated with usage data.
   */
  static fromUsage<C = string[]>(
    content: C,
    usage: OpenAI.Completions.CompletionUsage | undefined,
  ): TranslationOutput<C> {
    return new TranslationOutput(
      content,
      usage?.prompt_tokens,
      usage?.completion_tokens,
      usage?.prompt_tokens_details?.cached_tokens,
      usage?.total_tokens,
    );
  }
}
